DISTILLER:
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
  DIM_T: 512
  DIM_S: 512
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 120
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  ALPHA: 1.0
  BETA: 8.0
  TAU: 4.0
  WARMUP: 20
WSLL:
  TAU: 2.0
  ALPHA: 2.5